service: notification-service
frameworkVersion: '3'

package:
  individually: true

provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - ses:SendEmail
      Resource: arn:aws:ses:*
    - Effect: Allow
      Action:
        - sqs:ReceiveMessage
      Resource: ${self:custom.queues.mailQueue.arn}
  environment:
    REGION: ${self:provider.region}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'

custom:
  queues:
    mailQueue:
      name: !GetAtt MailQueue.QueueName
      arn: !GetAtt MailQueue.Arn
      url: !GetAtt MailQueue.QueueUrl
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node14'
    define: 
      'require.resolve': undefined
    platform: 'node'
    concurrency: 10

functions:
  - ${file(./src/infra/functions.yml)}

resources:
  - ${file(./src/infra/resources/MailQueue.yml)}

plugins: 
  - serverless-esbuild
      