Resources:
  AuctionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AuctionsTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: ending_at
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: GSI-status-ending_at
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: ending_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL            
            